### ISSUE TITLE
McAfee VirusScan Enterprise false positive

### ISSUE THREAD

**Issue by skvatboy** [OpenBoardView/OpenBoardView#178]
Hi 
McAfee detect OpenBoardView v 8.0 as GenericRXKM-ZL!7A4F08BFEF17

![billede](https://user-images.githubusercontent.com/5960870/82763681-b7934e00-9e09-11ea-9c99-f9ed8921e6c0.png)

**Comment by piernov** [comment]
Hi,
According to VirusTotal, McAfee is the only antivirus that triggers a false positive without even a proper code name, probably improper heuristics on their end.

We cannot invest the resources in taking care of issues caused by antiviruses themselves, but contributions are welcome.
McAfee should have a service to report false positive.
