### ISSUE TITLE
GenCAD board outline issue

### ISSUE THREAD

**Issue by swiftgeek** [OpenBoardView/OpenBoardView#248]
(originally posted in https://github.com/OpenBoardView/OpenBoardView/pull/219#issuecomment-1147291206)
I have prepared a file with a board outline that still has issues loading properly
[board-outline.zip](https://github.com/OpenBoardView/OpenBoardView/files/8843636/board-outline.zip)

<details>
  <summary>Screenshots with expected behaviour/current state</summary>
  
 Expected board outline
![board-outline-expected](https://user-images.githubusercontent.com/270845/172141682-bd4d3172-8986-4b8d-84b6-a34ae75e4d15.png)

Current OBV render:
![board-outline-current](https://user-images.githubusercontent.com/270845/172142072-510eb770-4edc-4007-9054-752894a8590e.png)
  
</details>

piernov's response in pull request adding GenCAD support: https://github.com/OpenBoardView/OpenBoardView/pull/219#issuecomment-1147744835

> There was something similar happening in BVR3 format due to having a segmented outline mode which OBV doesn't know how to handle, no idea if it's related but you can look at the discussion in #224 and the code in "BVR3File.cpp".

**Comment by inflex** [comment]
I suspect the problem is that the GenCAD outline usually is segment based, not a sequence of poly points. 

You've got two options that I can think of immediately;

1) Add segment-based outline + fill drawing versions of the existing outline/fill functions
2) Convert segment based outlines to polygon sequence ( note that internal holes will need to be handled either by "same point termination" or clockwise-anticlockwise path directions.

This is what it looks like in FlexBV ( which has the segment based rendering facility
![s](https://user-images.githubusercontent.com/5660591/173719711-ec389570-c27a-42de-924a-f3cf25550c5a.jpg)
 )

**Comment by martonmiklos** [comment]
So here is an example gencad forming a circle contour with 100 radius around the 100,100 point:
https://gist.github.com/martonmiklos/27564ca2fc0ac7108c7fccc117e1413a

This renders this way:
![kép](https://user-images.githubusercontent.com/1609182/174071357-3e69ce5c-d22f-4b92-af72-c4084ea6286f.png)
