### ISSUE TITLE
Keyboard Preferences in obv.conf not compatible

### ISSUE THREAD

**Issue by gerikerschi** [OpenBoardView/OpenBoardView#270]
If you save the key combination "command + F" in version 8.95.1, then "Super-F" is saved in obv.conf.
Since the newer versions (example 9.95.0) the key combination "command + F" is stored in the obv.conf "ModSuper-F".
So the versions are not compatible anymore.
As soon as one starts a new version, the old version can be started again only if the obv.conf is deleted or the entry with the stored "command + F" is removed.

**Comment by piernov** [comment]
Keyboard handling changed a little bit with 8.95.2 due to some changes in the GUI toolkit we use (ImGui), so full compatibility of configuration file indeed broke between 8.95.1 and 8.95.2, which were both beta releases. Custom keyboard bindings was introduced with a previous alpha release (versioned 9.0-alpha1 which would correspond to 8.90.0 with the new versioning scheme).
None of these versions were stable versions. Nothing should have been broken since 9.0.0 which is the first stable version to include custom keyboard bindings. So there is nothing to fix as far as I can see.
We will however try to keep forward compatibility of the configuration file for future versions, but not necessarily backward.
